title: DaBombDiggity
author: Vuk
email: vmarkeic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is not worth reading.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
